### ISSUE TITLE
Any idea why IE9 would not work?

### ISSUE THREAD

**Issue by vdclouis** [odiumediae/tagdog.js#3]

**Comment by odiumediae** [comment]
I used `Element.classList` which is not supported in IE9 (support starts with IE10). I'll implement a shim as soon as I've got the time (probably tonight, if not, tomorrow) and make sure I'll shim everything else that is not supported in IE9+.

I won't even start supporting IE8, but you're right, IE9 should be supported as it's still widely used. Shouldn't even be mildly hard to do.

I'm on Linux and I currently I can only test in IE10+, so I'd like you (or whoever else reads this and has native IE9 available) to provide some feedback, later.

For any other potential problems with IE, please post a new Issue.

Thanks.

**Comment by vdclouis** [comment]
:ok_hand:

**Comment by odiumediae** [comment]
I provided a cheap but nicely working shim for `Element.classList.add`, and looked through the code, but I didn't see anything else that should only be working in IE10+. This means, if I didn't miss anything, it should be working in IE9+ now, but as I cannot test it myself, please try it out yourself and give me some feedback, if you'd be so kind.

On a side note, I had to bump the version up a few notches, because versioning with Git, npm, etc. is real a pain in the ass.

**Comment by kriskbx** [comment]
I'm going to test IE9+ tonight. :)

**Comment by vdclouis** [comment]
Is the code used in your showcase the latest and greatest infused with some IE9 goodness?
Would be nice, that way we can test it easily :D

**Comment by odiumediae** [comment]
I must be doing something wrong with the versioning/tagging, I keep messing it up. I've now bumped it up to v0.1.5, now the IE9 fix is definitely in the latest version and the showcase is updated too: https://showcase.letmeco.de/tagdog/ (I had some aggressive Cloudflare caching going, and I changed that).

Sorry for the tagging/versioning troubles, I should read up on that thoroughly.

**Comment by odiumediae** [comment]
Has anybody tested IE9, yet?

**Comment by kriskbx** [comment]
Nope, sorry. My Windows machine won't boot at the moment. I'm goin to work on this on Saturday, maybe Sunday.
